// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.1
// source: proto/depth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepthLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Orders        uint32                 `protobuf:"varint,3,opt,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthLevel) Reset() {
	*x = DepthLevel{}
	mi := &file_proto_depth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthLevel) ProtoMessage() {}

func (x *DepthLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthLevel.ProtoReflect.Descriptor instead.
func (*DepthLevel) Descriptor() ([]byte, []int) {
	return file_proto_depth_proto_rawDescGZIP(), []int{0}
}

func (x *DepthLevel) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DepthLevel) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DepthLevel) GetOrders() uint32 {
	if x != nil {
		return x.Orders
	}
	return 0
}

type DepthMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstrumentToken uint32                 `protobuf:"varint,1,opt,name=instrument_token,json=instrumentToken,proto3" json:"instrument_token,omitempty"`
	Bids            []*DepthLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks            []*DepthLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	TimestampNs     int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	SequenceId      uint64                 `protobuf:"varint,5,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DepthMessage) Reset() {
	*x = DepthMessage{}
	mi := &file_proto_depth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthMessage) ProtoMessage() {}

func (x *DepthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthMessage.ProtoReflect.Descriptor instead.
func (*DepthMessage) Descriptor() ([]byte, []int) {
	return file_proto_depth_proto_rawDescGZIP(), []int{1}
}

func (x *DepthMessage) GetInstrumentToken() uint32 {
	if x != nil {
		return x.InstrumentToken
	}
	return 0
}

func (x *DepthMessage) GetBids() []*DepthLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *DepthMessage) GetAsks() []*DepthLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *DepthMessage) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *DepthMessage) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

var File_proto_depth_proto protoreflect.FileDescriptor

var file_proto_depth_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x74, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0a, 0x44, 0x65,
	0x70, 0x74, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x69,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x25,
	0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x04, 0x62, 0x69, 0x64, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4e, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42,
	0x68, 0x61, 0x76, 0x69, 0x6b, 0x32, 0x32, 0x30, 0x35, 0x2f, 0x4d, 0x4c, 0x2d, 0x42, 0x6f, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_depth_proto_rawDescOnce sync.Once
	file_proto_depth_proto_rawDescData = file_proto_depth_proto_rawDesc
)

func file_proto_depth_proto_rawDescGZIP() []byte {
	file_proto_depth_proto_rawDescOnce.Do(func() {
		file_proto_depth_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_depth_proto_rawDescData)
	})
	return file_proto_depth_proto_rawDescData
}

var file_proto_depth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_depth_proto_goTypes = []any{
	(*DepthLevel)(nil),   // 0: proto.DepthLevel
	(*DepthMessage)(nil), // 1: proto.DepthMessage
}
var file_proto_depth_proto_depIdxs = []int32{
	0, // 0: proto.DepthMessage.bids:type_name -> proto.DepthLevel
	0, // 1: proto.DepthMessage.asks:type_name -> proto.DepthLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_depth_proto_init() }
func file_proto_depth_proto_init() {
	if File_proto_depth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_depth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_depth_proto_goTypes,
		DependencyIndexes: file_proto_depth_proto_depIdxs,
		MessageInfos:      file_proto_depth_proto_msgTypes,
	}.Build()
	File_proto_depth_proto = out.File
	file_proto_depth_proto_rawDesc = nil
	file_proto_depth_proto_goTypes = nil
	file_proto_depth_proto_depIdxs = nil
}
