# configs/app.yaml
server:
  http_port: 8000
  websocket_path: "/ws"
  # If WebSocket runs on a separate port:
  # websocket_port: 8081

log:
  level: warn # debug, info, warn, error
  output: logs/app.log # stdout, file (for production, typically stdout for Docker)
  # If output is 'file':
  # file_path: logs/app.log
  # max_size_mb: 100
  # max_backups: 5
  # max_age_days: 7
  # compress: true

ingestion:
  market_data_batch_size: 100 # For your local setup, 500-1000 is good
  market_data_flush_interval_ms: 20 # 50ms for low latency
  max_tick_sequence_cache_duration_s: 2 # 2 seconds
  tick_sequence_cleanup_interval_s: 1 # This must be a positive integer
  db_worker_count: 16 # Number of workers for database operations
  db_flush_channel_size: 10000
  ws_broadcast_worker_count: 8 # Number of workers for WebSocket broadcasting
  ws_broadcast_channel_size: 20000
  redis_reconnect_initial_delay_ms: 1000 # Initial delay for Redis reconnection
  redis_reconnect_max_delay_ms: 5000 # Maximum delay for Redis reconnection
  redis_reconnect_max_attempts: 10

monitor:
  broadcast_interval: 5s # e.g., 5 seconds

candles:
  intervals: ["1m", "5m", "15m", "1h"] # Define intervals for candlestick generation

# Other application-wide settings
graceful_shutdown_timeout_seconds: 15

market:
  simulate: true
  simulation_speed_multiplier: 8.0 # This can be set to any float value >= 0.1